Spock Bug Tracker/Controllers/ChartsController.cs
using Spock_Bug_Tracker.Models;
using Spock_Bug_Tracker.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Spock_Bug_Tracker.Controllers
{
    public class ChartsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        public JsonResult GetRealMorrisData()
        {
            var dataSet = new List<MorrisBarChartData>();
            foreach(var ticketStatus in db.TicketStatuses.ToList())
            {
                var value = db.TicketStatuses.Find(ticketStatus.Id).Tickets.Count();
                dataSet.Add(new MorrisBarChartData { label = ticketStatus.Name, value = value });
            }

            return Json(dataSet);
        }
        public JsonResult GetRealFusionByType()
        {
            var dataSet = new List<FusionPieChartData>();
            foreach (var ticketTypes in db.TicketTypes.ToList())
            {
                var value = db.TicketTypes.Find(ticketTypes.Id).Tickets.Count();
                dataSet.Add(new FusionPieChartData { label = ticketTypes.Name, value = value.ToString() });
            }

            return Json(dataSet);
        }
    }
}

Spock Bug Tracker/Controllers/HomeController.cs
using Spock_Bug_Tracker.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Threading.Tasks;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;

namespace Spock_Bug_Tracker.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Login()
        {
            return View();
        }
        public ActionResult DemoUser()
        {
            return View();
        }

        public ActionResult Register()
        {
            return View();
        }
        public ActionResult DashBoard()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            EmailModel model = new EmailModel();
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Contact(EmailModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    //string interpelation
                    var from = $"{model.FromEmail}<{WebConfigurationManager.AppSettings["emailto"]}>";

                    var email = new MailMessage(from, WebConfigurationManager.AppSettings["emailto"])
                    {
                        Subject = model.Subject,
                        Body = model.Body,
                        IsBodyHtml = true
                    };
                    var svc = new PersonalEmail();
                    await svc.SendAsync(email);

                    return View(new EmailModel());
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                    await Task.FromResult(0);
                }
            }
            return View(model);
        }
    }
}

Spock Bug Tracker/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Spock Bug Tracker/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Spock Bug Tracker/Views/Home/DashBoard.cshtml
@using Spock_Bug_Tracker.Models
@using Microsoft.AspNet.Identity
@using Spock_Bug_Tracker.Helper

@{
    var userId = User.Identity.GetUserId();
    var db = new ApplicationDbContext();
    var user = db.Users.Find(userId);
    var notificationHelper = new NotificationHelper();
    var ticketHelper = new TicketHelper();
}
<header class="page-header">
    <h2>Dashboard</h2>

    <div class="right-wrapper pull-right">
        <ol class="breadcrumbs">
            <li>
                <a href="index.html">
                    <i class="fa fa-home"></i>
                </a>
            </li>
            <li><span>Dashboard</span></li>
        </ol>

        <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
    </div>
</header>
<!--Bar Chart-->
<div class="row">
    <div class="col-md-6">
        <section class="panel">
            <header class="panel-heading">
                <div class="panel-actions">
                    <a href="#" class="fa fa-caret-down"></a>
                    <a href="#" class="fa fa-times"></a>
                </div>

                <h2 class="panel-title">Ticket Status</h2>
                <p class="panel-subtitle">This chart represents all tickets by status.</p>
            </header>
            <div class="panel-body">
                <div class="chart chart-md" id="RealMorrisBarChart"></div>
            </div>
        </section>
    </div>
    <!--Pie Chart-->
    <div class="col-md-6">
        <section class="panel">
            <header class="panel-heading">
                <div class="panel-actions">
                    <a href="#" class="fa fa-caret-down"></a>
                    <a href="#" class="fa fa-times"></a>
                </div>

                <h2 class="panel-title">Ticket Type</h2>
                <p class="panel-subtitle">This pie chart represents all ticket types.</p>
            </header>
            <div class="panel-body">
                <div class="chart chart-md" id="Fusion3dPieChart"></div>
            </div>
        </section>
    </div>
</div>
<div class="row">
    <div class="col-md-6 col-lg-12 col-xl-6">
        <div class="row">
            <div class="col-md-12 col-lg-6 col-xl-6">
                <section class="panel panel-featured-left panel-featured-primary">
                    <div class="panel-body">
                        <div class="widget-summary">
                            <div class="widget-summary-col widget-summary-col-icon">
                                <div class="summary-icon bg-primary">
                                    <i class="fa fa-ticket"></i>
                                </div>
                            </div>
                            <div class="widget-summary-col">
                                <div class="summary">
                                    @if (User.IsInRole("Admin"))
                                    { 
                                        <h4>TOTAL TICKETS</h4>
                                     }
                                     else
                                     {
                                        <h4>MY TICKETS</h4>
                                     }
                                    

                                    
                                        <div class="info">
                                            <strong class="amount">@ticketHelper.CountMyTickets(userId)</strong>
                                        </div>
                                   
                                    </div>
                                <div class="summary-footer">
                                    <a href="@Url.Action("Index", "Tickets")">(View All)</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
            <div class="col-md-12 col-lg-6 col-xl-6">
                <section class="panel panel-featured-left panel-featured-secondary">
                    <div class="panel-body">
                        <div class="widget-summary">
                            <div class="widget-summary-col widget-summary-col-icon">
                                <div class="summary-icon bg-primary">
                                    <i class="fa fa-group"></i>
                                </div>
                            </div>
                            <div class="widget-summary-col">
                                <div class="summary">
                                    @if (User.IsInRole("Admin"))
                                    {
                                        <h4>TOTAL IMMEDIATE TICKETS</h4>
                                    }
                                    else
                                    {
                                        <h4>MY IMMEDIATE TICKETS</h4>
                                    }
                                    <div class="info">
                                        <strong class="amount">@ticketHelper.CountMyImmediateTickets(userId)</strong>
                                    </div>
                                </div>
                                <div class="summary-footer">
                                    <a href="@Url.Action("Index", "Tickets")">(View All)</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>

        </div>
    </div>
</div>
<!-- start: page -->
<div class="row">
    <div class="col-xl-3 col-lg-12">
        <section class="panel panel-transparent">
            <header class="panel-heading">
                <div class="panel-actions">
                    <a href="#" class="fa fa-caret-down"></a>
                    <a href="#" class="fa fa-times"></a>
                </div>

                <h2 class="panel-title">My Profile</h2>
            </header>

            <div class="panel-body">
                <section class="panel panel-group">
                    @if (User.Identity.IsAuthenticated)
                    {

                        var AvatarUrl = db.Users.Find(userId).AvatarUrl;
                        var fullName = db.Users.Find(userId).FullName;
                        var roleHelper = new UserRolesHelper();
                        <header class="panel-heading bg-primary">
                            <div class="widget-profile-info">
                                <div class="profile-picture">
                                    <img src="@AvatarUrl">
                                </div>
                                <div class="profile-info">
                                    <h4 class="name text-semibold">@fullName</h4>
                                    <h5 class="role">
                                        @if (roleHelper.ListUserRoles(userId).FirstOrDefault() == "Project Manager")
                                        {
                                            <span>Project Manager</span>
                                        }
                                        else
                                        {
                                            @roleHelper.ListUserRoles(userId).FirstOrDefault();
                                        }
                                    </h5>
                                    <div class="profile-footer">
                                        <a href="@Url.Action("Index", "Manage")">(edit profile)</a>
                                    </div>
                                </div>
                            </div>
                        </header>
                    }
                    <div id="accordion">
                        <div class="panel panel-accordion panel-accordion-first">
                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapse1One">
                                        <i class="fa fa-check"></i> Tasks
                                    </a>
                                </h4>
                            </div>
                            <div id="collapse1One" class="accordion-body collapse in">
                                <div class="panel-body">
                                    <ul class="widget-todo-list">

                                        <li>
                                            <div class="checkbox-custom checkbox-default">
                                                <input type="checkbox" id="todoListItem6" class="todo-check">
                                                <label class="todo-label" for="todoListItem6"><span>Test task 1</span></label>
                                            </div>
                                            <div class="todo-actions">
                                                <a class="todo-remove" href="#">
                                                    <i class="fa fa-times"></i>
                                                </a>
                                            </div>
                                        </li>
                                        <li>
                                            <div class="checkbox-custom checkbox-default">
                                                <input type="checkbox" id="todoListItem6" class="todo-check">
                                                <label class="todo-label" for="todoListItem6"><span>Test task 2</span></label>
                                            </div>
                                            <div class="todo-actions">
                                                <a class="todo-remove" href="#">
                                                    <i class="fa fa-times"></i>
                                                </a>
                                            </div>
                                        </li>
                                        <li>
                                            <div class="checkbox-custom checkbox-default">
                                                <input type="checkbox" id="todoListItem6" class="todo-check">
                                                <label class="todo-label" for="todoListItem6"><span>Test task 3</span></label>
                                            </div>
                                            <div class="todo-actions">
                                                <a class="todo-remove" href="#">
                                                    <i class="fa fa-times"></i>
                                                </a>
                                            </div>
                                        </li>
                                    </ul>
                                    <hr class="solid mt-sm mb-lg">
                                    <form method="get" class="form-horizontal form-bordered">
                                        <div class="form-group">
                                            <div class="col-sm-12">
                                                <div class="input-group mb-md">
                                                    <input type="text" class="form-control">
                                                    <div class="input-group-btn">
                                                        <button type="button" class="btn btn-primary" tabindex="-1">Add</button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </section>
    </div>
</div>
@section scripts{

    <script>
     $(function () {
        $.post('@Url.Action("GetRealMorrisData","Charts")').then(function (response) {
            new Morris.Bar({
                 element: 'RealMorrisBarChart',
                data: response,
                gridTextSize: 10,
                xLabelAngle: 65,
                xkey: 'label',
                ykeys: ['value'],
                labels: ['Ticket Count'],
                resize: true
            });
        });
     });

    </script>
    <script>

        $(function () {
            var url = '@Url.Action("GetRealFusionByType","Charts")';

            $.post(url).then(function (response) {
                var revenueChart = new FusionCharts({
                    type: "pie3d",
                    renderAt: "Fusion3dPieChart",
                    width: "%100",
                    height: "%100",
                    dataFormat: "json",
                    dataSource: {
                        "chart": {
                            caption: "",
                            subCaption: "",
                            xAxisName: "Type",
                            yAxisName: "Count",
                            numberSuffix: "",
                            theme: "fusion"
                        },
                        "data": response
                    }
                }).render();
            });
        });
    </script>
}

Spock Bug Tracker/Views/Home/DemoUser.cshtml
@{
    Layout = null;
}

<!doctype html>
<html class="fixed">
<head>

    <!-- Basic -->
    <meta charset="UTF-8">

    <meta name="keywords" content="HTML5 Admin Template" />
    <meta name="description" content="Porto Admin - Responsive HTML5 Template">
    <meta name="author" content="okler.net">

    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

    <!-- Web Fonts  -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800|Shadows+Into+Light" rel="stylesheet" type="text/css">

    <!-- Vendor CSS -->
    <link href="~/Style/bootstrap.css" rel="stylesheet" />
    <link href="~/Style/font-awesome.css" rel="stylesheet" />
    <link href="~/Style/magnific-popup.css" rel="stylesheet" />
    <link href="~/Style/datepicker3.css" rel="stylesheet" />

    <!-- Theme CSS -->
    <link href="~/Style/theme.css" rel="stylesheet" />

    <!-- Skin CSS -->
    <link href="~/Style/default.css" rel="stylesheet" />
    <!-- Theme Custom CSS -->
    <link href="~/Style/theme-custom.css" rel="stylesheet" />

    <!-- Head Libs -->
    <script src="~/Scripts/modernizr.js"></script>

</head>
<body>
    <!-- start: page -->
   

    <section class="body-sign">
        <div class="center-sign">
            <a href="/" class="logo pull-left">
                
            </a>

            <div class="panel panel-sign">
                <div class="panel-title-sign mt-xl text-right">
                    <h2 class="title text-uppercase text-bold m-none"><i class="fa fa-user mr-xs"></i>Demo Login</h2>
                </div>
                <div class="panel-body">
                    <div class="row">
                        @using (Html.BeginForm("DemoLoginAsync", "Account", FormMethod.Post))
                        {
                            @Html.AntiForgeryToken()
                            @Html.Hidden("DemoEmail", "DemoAdminEmail")
                            <div class="col-md-6">
                                <section class="panel">
                                    <header class="panel-heading bg-dark">
                                        <div class="panel-heading-icon bg-danger mt-sm">
                                            <i class="fa fa-eye"></i>
                                        </div>
                                    </header>
                                    <div class="panel-body">
                                        <h3 class="text-semibold mt-none text-center">Admin</h3>
                                        <p class="text-center">The Admin has full permissions across the full application.</p>
                                        <button type="submit" class="btn btn-xs btn-danger center-block">Login</button>
                                    </div>
                                </section>
                            </div>
                        }

                        @using (Html.BeginForm("DemoLoginAsync", "Account", FormMethod.Post))
                        {
                            @Html.AntiForgeryToken()
                            @Html.Hidden("DemoEmail", "DemoProjectManagerEmail")
                            <div class="col-md-6">
                                <section class="panel">
                                    <header class="panel-heading bg-dark">
                                        <div class="panel-heading-icon bg-danger mt-sm">
                                            <i class="fa fa-group"></i>
                                        </div>
                                    </header>
                                    <div class="panel-body">
                                        <h3 class="text-semibold mt-none text-center">Project Manager</h3>
                                        <p class="text-center">The Project Manager is the only role that can be on mutliple projects and is the lead of the projects.</p>
                                        <button type="submit" class="btn btn-xs btn-danger center-block">Login</button>
                                    </div>
                                </section>
                            </div>
                        }
                        </div>

                    <div class="row">
                        @using (Html.BeginForm("DemoLoginAsync", "Account", FormMethod.Post))
                        {
                            @Html.AntiForgeryToken()
                            @Html.Hidden("DemoEmail", "DemoDeveloperEmail")
                            <div class="col-md-6">
                                <section class="panel">
                                    <header class="panel-heading bg-dark">
                                        <div class="panel-heading-icon bg-danger mt-sm">
                                            <i class="fa fa-code"></i>
                                        </div>
                                    </header>
                                    <div class="panel-body">
                                        <h3 class="text-semibold mt-none text-center">Developer</h3>
                                        <p class="text-center">The develoeper is the workhorse. Who works on tickets.</p>
                                        <button type="submit" class="btn btn-xs btn-danger center-block">Login</button>
                                    </div>
                                </section>
                            </div>
                        }

                        @using (Html.BeginForm("DemoLoginAsync", "Account", FormMethod.Post))
                        {
                        @Html.AntiForgeryToken()
                        @Html.Hidden("DemoEmail", "DemoSubmitterEmail")
                        <div class="col-md-6">
                            <section class="panel">
                                <header class="panel-heading bg-dark">
                                    <div class="panel-heading-icon bg-danger mt-sm">
                                        <i class="fa fa-envelope"></i>
                                    </div>
                                </header>
                                <div class="panel-body">
                                    <h3 class="text-semibold mt-none text-center">Submitter</h3>
                                    <p class="text-center">The only role with the ability to create new tickets.</p>
                                    <button type="submit" class="btn btn-xs btn-danger center-block">Login</button>
                                </div>
                            </section>
                        </div>
                        }
                    </div>

                </div>
            </div>
        </div>
    </section>





                    


                    <!-- end: page -->
                    <!-- Vendor -->
                    <script src="~/Scripts/jquery.js"></script>
                    <script src="~/Scripts/jquery.browser.mobile.js"></script>
                    <script src="~/Scripts/bootstrap.js"></script>
                    <script src="~/Scripts/nanoscroller.js"></script>
                    <script src="~/Scripts/bootstrap-datepicker.js"></script>
                    <script src="~/Scripts/magnific-popup.js"></script>
                    <script src="~/Scripts/jquery.placeholder.js"></script>

                    <!-- Theme Base, Components and Settings -->
                    <script src="~/Scripts/theme.js"></script>

                    <!-- Theme Custom -->
                    <script src="~/Scripts/theme.custom.js"></script>

                    <!-- Theme Initialization Files -->
                    <script src="~/Scripts/theme.init.js"></script>

</body>
</html>